### ISSUE TITLE
EditorAttributes not working with class inherited from NetworkBehaviour

### ISSUE THREAD

**Issue by W3ktor** [v0lt13/EditorAttributes#16]
I'm using Netcode for Gameobjects and I think NetworkBehaviour class uses other PropertyDrawer than the default MonoBehaviour.
Not sure if this can be considered as a potentional fix in the future because Netcode is changing constantly but it would be great to hear any suggestion to solve this issue.

This image shows one example but basically EditorAttributes are unusable in any networked class.
![image](https://github.com/user-attachments/assets/1578fa4e-626c-41de-88c6-21ecd998bd4e)

**Comment by v0lt13** [comment]
Yeah I know about this. I'm guessing netcode extends the editor class and does some ImGUI stuff there or it has a custom property drawer thats using ImGUI. I will have to research to see if its possible to detect and draw ImGUI properties with UI toolkit but there is no guarantee. The only other solution is to manually find and modify that drawer to use UI toolkit but for that you will have to clone the package in your project and handle any merges with new updates which can be a pain. Or just wait until unity decides to use UI toolkit consistently for their editors.

**Comment by W3ktor** [comment]
Thanks for your reply, I'll try somethin custom.

**Comment by v0lt13** [comment]
Ok after further research it seems that the NetworkBehaviour editor class uses ImGUI to draw all properties in the inspector and if you use a property drawer that makes use of UI toolkit, it will show the No GUI Implemented text because you cannot draw UI Toolkit stuff with ImGUI. So the only solution to this is to migrate the NetworkBehaviour editor to UI toolkit or create an ImGUI version for each attribute in the package. 

I recommend just submitting a ticket to unity that UI toolkit property drawers don't draw when using them in a NetworkBehaviour and hope they handle it themselves.
