### ISSUE TITLE
error CS0246: The type or namespace name 'Newtonsoft' could not be found

### ISSUE THREAD

**Issue by Theadd** [v0lt13/EditorAttributes#3]
Hi there,

```
Assets\EditorAttributes\Editor\Scripts\Drawers\ButtonDrawer.cs(6,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
```

Just installed the package from the unity asset store on a Unity Editor 2022.3 LTS project using the 3D Core URP template, I got rid of the error by changing the `Newtonsoft.Json` import but I've not tested it out yet.

```csharp
// using Newtonsoft.Json;
using Unity.Plastic.Newtonsoft.Json;
```

Nice stuff, thank you!

**Comment by v0lt13** [comment]
This issue was because the newtonsoft json package didnt install with the editor attributes package for some reason (perhaps i forgot to include the package manifest in the asset store), what you did is use the newtonsoft json library that came with the visual scripting package which is pretty much the same library, to fix the issue just to go the package manager -> add package by name -> and paste this "com.unity.nuget.newtonsoft-json"
